name: Deploy to DEV

on:
  workflow_call:
  inputs:
    AWS_ACCOUNT:
      type: string
      required: true
    AWS_REGION:
      type: string
      required: false
      default: 'eu-central-1'
    secrets:
      AWS_OIDC_ROLE_ARN:
        required: true
      NPM_READ_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy [dev]
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_REGION: ${{ inputs.AWS_REGION }}
      AWS_ACCOUNT: ${{ inputs.AWS_ACCOUNT }}
      AWS_SSM_STAGE: dev
      CDK_DEBUG: true
      DYNAMO_REMOVAL_POLICY: destroy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Backend: Read .nvmrc'
        run: echo NODE_VERSION_BACKEND=`cat backend/.nvmrc` >> $GITHUB_ENV

      - name: 'Infrastructure: Read .nvmrc'
        run: echo NODE_VERSION_INFRASTRUCTURE=`cat infrastructure/.nvmrc` >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION_INFRASTRUCTURE }}
          registry-url: 'https://npm.pkg.github.com'

      - name: 'Infrastructure: Install NPM Dependencies'
        run: npm install --prefix infrastructure
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

      - name: CDK bootstrap
        run: npm run bootstrap --prefix infrastructure

      - name: CDK deploy
        run: npm run deploy --prefix infrastructure
