name: CDK Deployment

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        type: string
        required: false
        default: eu-central-1
    secrets:
      DEV_AWS_ACCESS_KEY_ID:
        required: true
      DEV_AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm ci

      - run: npm run build --if-present

      - name: Synth stack
        run: npx cdk synth

      - name: Deploy stack
        run: npx cdk deploy --require-approval never
