name: Deployment

on:
  workflow_call:
    inputs:
      access_key:
        required: true
        type: string
      secret_key:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
